
require('./assets/Script/NPC/CattyController');
require('./assets/Script/NPC/CattySpawner');
require('./assets/Script/NPC/GoblinController');
require('./assets/Script/NPC/GoblinSpawner');
require('./assets/Script/NPC/NPCWanderCatty');
require('./assets/Script/NPC/NPCWanderGoblin');
require('./assets/Script/PauseManager');
require('./assets/Script/Player/GamepadControls');
require('./assets/Script/Player/IInputControls');
require('./assets/Script/Player/KeyboardControls');
require('./assets/Script/Player/KeyboardControls2');
require('./assets/Script/Player/Level2icecream1');
require('./assets/Script/Player/Level2icecream2');
require('./assets/Script/Player/PlayerController 2');
require('./assets/Script/Player/PlayerController');
require('./assets/Script/debug');
require('./assets/Script/scene/ScorePersist');
require('./assets/Script/scene/score-scene');
require('./assets/Script/scene/uiManager');
